services:
  - type: web
    name: knowlarity-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: daphne -b 0.0.0.0 -p 8000 knowlarity_api.asgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: knowlarity_api.settings
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        value: django-insecure-dgjx&-_m_ne+%d+cs3jj1b_%7dlw9-7z34!9@wz&w^+gcwus)p

